import type { NextFunction, Request, Response } from "express";
export declare const inviteUser: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const cancelInvite: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const sendJoinRequest: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const cancelJoinRequest: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const acceptInvite: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const rejectInvite: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const acceptJoinRequest: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const rejectJoinRequest: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getInvites: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getTeamInvites: (req: Request, res: Response, next: NextFunction) => Promise<void>;
