import { NextFunction, Request, Response } from "express";
export declare const updateSubmissionStatus: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const RejectSubmissionStatus: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getTeam: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getProb: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const listTeamsWithBugRound: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const updateBugRoundScore: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getAllApprovedTeams: (_req: Request, res: Response) => Promise<void>;
export declare const updateTeamScore: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getAllRounds: (_req: Request, res: Response) => Promise<void>;
export declare const updateTeamDeployStatus: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getAverageDenominatorConfig: (_req: Request, res: Response) => Promise<void>;
export declare const getMyProblems: (req: Request, res: Response) => Promise<void>;
