import type { NextFunction, Request, Response } from "express";
export declare const getTeam: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const createTeam: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const deleteTeam: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const leaveTeam: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const listTeams: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const removeMember: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getProgress: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const listStages: (_: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const makeSubmission: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const deleteSubmission: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getSubmission: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const extractPublicId: (url: string) => string;
